---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

steps:
- name: sync
  image: thegeeklab/git-batch:latest
  commands:
  - git-batch

- name: build
  image: owncloudci/hugo:0.69.2
  commands:
  - hugo

- name: publish
  image: plugins/gh-pages:latest
  settings:
    pages_directory: public/
    password:
      from_secret: github_token
    target_branch: master
    username:
      from_secret: github_username
  when:
    ref:
    - refs/heads/source

trigger:
  ref:
  - refs/heads/source
  - refs/pull/**

...
